#!/bin/sh

stribog -i \
	-r ~/dev \
	-r ~/.config/nvim \
	-f asset  \
	-f resource \
	-f test \
	-f conf \
	-f logs \
	-f .git \
	-f .next \
	-f .swc \
	-f node_modules \
	-f e2e \
	-f build \
	-f target \
	-f dist | fzf
