#!/bin/sh

if [ "$#" -eq 1 ]; then
    selected="$1"
else
    if [ -t 0 ]; then
        selected=$(find ~/Slike/WP -maxdepth 1 -type f -name "*.jpg" | fzf)
    else
        read selected
    fi
fi

# Check if the selected file exists
if [ ! -f "$selected" ]; then
    echo "Error: File not found: $selected"
    exit 1
fi

# Compute the average color of the image as a hex value
average_color=$(convert $selected -scale 1x1\! -format '%[pixel:u]' info:- \
	| sed -e 's/srgb(\([0-9.]*\)%,\([0-9.]*\)%,\([0-9.]*\)%)/\1 \2 \3/' \
	| awk '{printf "#%02x%02x%02x\n", $1*2.55, $2*2.55, $3*2.55}')

feh --bg-max --image-bg "$average_color" "$selected"
echo $selected > ~/.bg-image

screen_size=$(xdpyinfo | awk '/dimensions/ {print $2}')
convert $selected -resize "$screen_size" -gravity center -extent "$screen_size" -background "$average_color" -flatten ~/lockscreen.png

# nohup betterlockscreen -u ~/lockscreen.png > /dev/null 2>&1 &
