#!/usr/bin/env bash

if [ -d /mnt/c/ ]; then
    # Find Windows Terminal directory
    terminal_dir=$(find "$(wslpath $(wslvar USERPROFILE))/AppData/Local/Packages/" -maxdepth 1 -type d -name "Microsoft.WindowsTerminal*")
    # Construct path to settings.json
    settings_file="$terminal_dir/LocalState/settings.json"
    # Ensure write permissions
    chmod +w "$settings_file"
    # Use jq to modify the JSON and save to a temporary file
    opacity=$(jq '.profiles.list[2].backgroundImageOpacity' "$settings_file")
    # Ensure opacity is treated as a number
    opacity=${opacity//[^0-9]/}
    if [ "$opacity" -eq "0" ]; then
        jq '.profiles.list[].backgroundImageOpacity = 0.2' "$settings_file" > temp_settings.json
    else
        jq '.profiles.list[].backgroundImageOpacity = 0' "$settings_file" > temp_settings.json
    fi
    # Replace original settings.json with modified version
    mv temp_settings.json "$settings_file"
else
    # Change line background-opacity in ~/dev/.dotfiles/.config/ghostty/config
    # Extract opacity value
    opacity=$(grep "background-opacity" ~/dev/.dotfiles/.config/ghostty/config | awk '{print $3}')
    # Ensure opacity is treated as a number
    opacity=${opacity//[^0-9.]/}
    if [ "$opacity" == "1" ]; then
        echo "Setting opacity to 0.85"
        sed -i 's/background-opacity = 1/background-opacity = 0.85/' ~/dev/.dotfiles/.config/ghostty/config
    else
        echo "Setting opacity to 1"
        sed -i 's/background-opacity = 0.85/background-opacity = 1/' ~/dev/.dotfiles/.config/ghostty/config
    fi
fi

