#!/bin/sh

stribog -i \
	-r ~/dev \
	-r ~/Slike/WP \
	-f .gradle  \
	-f .mvn  \
	-f asset  \
	-f resource \
	-f mythsim \
	-f cmake \
	-f test \
	-f conf \
	-f logs \
	-f .git \
	-f .next \
	-f .astro \
	-f .settings \
	-f .swc \
	-f .idea \
	-f node_modules \
	-f bin \
	-f e2e \
	-f build \
	-f target \
	-f dist | fzf
