#!/usr/bin/env bash

# Flag -t "path" is for target directory
if [[ $# -eq 2 ]]; then
    target=$2
else
    target=~/dev
fi

dirs=$(stribog-options $2)

echo "$dirs" | fzf --reverse --preview 'echo {}' --preview-window=right:30%:wrap --preview="ls {}"
