#!/usr/bin/env bash

selected=$(stribog-select -t $(pwd))

# Open dir in new tmux page with name of the dir
selected_name=$(basename "$selected" | tr . _)
tmux new-window -n $selected_name -c "$selected"
